
import "antd/dist/reset.css";
import '@ant-design/v5-patch-for-react-19';
import { Inter } from "next/font/google";
import { ConfigProvider } from "antd";
import { AuthProvider } from "@/shared/providers/AuthProvider";
import "./globals.css";
import AppLayout from "@/widgets/layouts/ui/AppLayout";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ConfigProvider
            theme={{
              token: {
                colorPrimary: "#fa8c16",
                colorLink: "#fa8c16",
                colorLinkHover: "#fa8c16",
                colorLinkActive: "#fa8c16",
              },
              components: {
                Button: {
                  colorPrimary: "#fa8c16",
                  colorPrimaryHover: "#ffb366",
                },
                Radio: {
                  colorPrimary: "#fa8c16",
                },
                Upload: {
                  colorPrimary: "#fa8c16",
                  colorPrimaryHover: "#ffb366",
                },
              },
            }}
          >
            <AppLayout>{children}</AppLayout>

          </ConfigProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
