"use client";

import '@ant-design/v5-patch-for-react-19';
import { Inter } from "next/font/google";
import { ConfigProvider } from "antd";
import { SessionProvider } from "next-auth/react";
import { AuthProvider } from "@/providers/AuthProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <AuthProvider>
            <ConfigProvider
              theme={{
                token: {
                  colorPrimary: "#ff8533", // Update primary color to match FPT brand
                  borderRadius: 6,
                  colorLink: "#ff8533",
                  colorPrimaryHover: "#ffa366",
                },
                components: {
                  Layout: {
                    headerBg: '#ffffff',
                    footerBg: '#27272a',
                    footerPadding: '48px 24px 24px'
                  },
                  Menu: {
                    horizontalItemSelectedColor: '#ff8533',
                    horizontalItemHoverColor: '#ff8533',
                    itemHoverColor: '#ff8533'
                  }
                }
              }}
            >
              {children}
            </ConfigProvider>
          </AuthProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
